=== 00mjk/SubEthaEdit/documentation/manual/etc/documentation.dtd
<!ELEMENT chapter (#PCDATA | section | paragraph | image | sourcecode | list | note | example)*>
	<!ATTLIST chapter name CDATA #IMPLIED>
	<!ATTLIST chapter edition CDATA #IMPLIED>
	<!ATTLIST chapter id ID #REQUIRED>
	<!ATTLIST chapter edition_lite (yes | no) "yes">
	<!ATTLIST chapter edition_pro (yes | no) "yes">
	<!ATTLIST chapter edition_se (yes | no) "yes">
	<!ATTLIST chapter edition_ee (yes | no) "yes">

<!ELEMENT section (#PCDATA | subsection | paragraph | sourcecode | list | note | example | image)*>
	<!ATTLIST section name CDATA #REQUIRED>
	<!ATTLIST section id CDATA #REQUIRED>
	<!ATTLIST section anchor CDATA #IMPLIED>
	<!ATTLIST section edition_lite (yes | no) "yes">
	<!ATTLIST section edition_pro (yes | no) "yes">
	<!ATTLIST section edition_se (yes | no) "yes">
	<!ATTLIST section edition_ee (yes | no) "yes">

<!ELEMENT subsection (#PCDATA | paragraph | sourcecode | list | note | example | image)*>
	<!ATTLIST subsection name CDATA #IMPLIED>
	<!ATTLIST section id CDATA #REQUIRED>
	<!ATTLIST subsection anchor CDATA #IMPLIED>
	<!ATTLIST subsection id CDATA #IMPLIED>
	<!ATTLIST subsection edition_lite (yes | no) "yes">
	<!ATTLIST subsection edition_pro (yes | no) "yes">
	<!ATTLIST subsection edition_se (yes | no) "yes">
	<!ATTLIST subsection edition_ee (yes | no) "yes">

<!ELEMENT paragraph (#PCDATA | phrase | nameofsoftware | link | reference)*>
	<!ATTLIST paragraph lead CDATA #IMPLIED>
	<!ATTLIST paragraph name CDATA #IMPLIED>
	<!ATTLIST paragraph edition_lite (yes | no) "yes">
	<!ATTLIST paragraph edition_pro (yes | no) "yes">
	<!ATTLIST paragraph edition_se (yes | no) "yes">
	<!ATTLIST paragraph edition_ee (yes | no) "yes">

<!ELEMENT phrase (#PCDATA | nameofsoftware | link | reference)*>
	<!ATTLIST phrase
		edition_lite (yes | no) "yes"
		edition_pro (yes | no) "yes"
		edition_se (yes | no) "yes"
		edition_ee (yes | no) "yes"
	>
	
<!ELEMENT sourcecode (#PCDATA | phrase | nameofsoftware | link | reference)*>
	<!ATTLIST sourcecode
		edition_lite (yes | no) "yes"
		edition_pro (yes | no) "yes"
		edition_se (yes | no) "yes"
		edition_ee (yes | no) "yes"
	>

<!ELEMENT list (#PCDATA | item)*>
	<!ATTLIST list
		edition_lite (yes | no) "yes"
		edition_pro (yes | no) "yes"
		edition_se (yes | no) "yes"
		edition_ee (yes | no) "yes"
	>

<!ELEMENT item (#PCDATA | phrase | link | reference | nameofsoftware)*>
	<!ATTLIST item name CDATA #IMPLIED>
	<!ATTLIST item
		edition_lite (yes | no) "yes"
		edition_pro (yes | no) "yes"
		edition_se (yes | no) "yes"
		edition_ee (yes | no) "yes"
	>

<!ELEMENT note (#PCDATA | link | reference | phrase | nameofsoftware)*>
	<!ATTLIST note
		edition_lite (yes | no) "yes"
		edition_pro (yes | no) "yes"
		edition_se (yes | no) "yes"
		edition_ee (yes | no) "yes"
	>

<!ELEMENT example (#PCDATA | link | reference | phrase | nameofsoftware)*>
	<!ATTLIST example
		edition_lite (yes | no) "yes"
		edition_pro (yes | no) "yes"
		edition_se (yes | no) "yes"
		edition_ee (yes | no) "yes"
	>

<!ELEMENT image (#PCDATA)>
	<!ATTLIST image
		name 		CDATA #IMPLIED
		src			CDATA #IMPLIED
		src_html		CDATA #IMPLIED
		align		(left | center | right) "center"
		scaling		CDATA "8cm"
	>
	<!ATTLIST image
		edition_lite (yes | no) "yes"
		edition_pro (yes | no) "yes"
		edition_se (yes | no) "yes"
		edition_ee (yes | no) "yes"
	>
	
<!ELEMENT link (#PCDATA)>
	<!ATTLIST link
		href CDATA #REQUIRED
	>

<!ELEMENT reference (#PCDATA | nameofsoftware)*>
	<!ATTLIST reference
		chapter CDATA #REQUIRED
		section CDATA #IMPLIED
		subsection CDATA #IMPLIED
	>
	<!ATTLIST reference edition_lite (yes | no) "yes">
	<!ATTLIST reference edition_pro (yes | no) "yes">
	<!ATTLIST reference edition_se (yes | no) "yes">
	<!ATTLIST reference edition_ee (yes | no) "yes">

=== 00mjk/SubEthaEdit/documentation/manual/SubEthaEdit/xml/widgets.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE chapter SYSTEM "../../etc/documentation.dtd">
<chapter name="Widgets" id="widgets" edition_le="no" edition_pe="no">
	<paragraph>${software} comes with two handy Dashboard widgets that allow you to jot down
	notes and store them into your database and to search your database at any time simply by
	visiting the Dashboard.</paragraph>
	<section name="DEVONjot Pro" id="devonjotpro">
		<paragraph>The DEVONjot Pro allows you to take notes and send these to ${software}.
		That's all it does. However, it can be configured to send the note to a particular
		database and group. This would allow you to open multiple widgets configured for
		different purposes.</paragraph>
		<subsection name="Front Side" id="devonjotpro_front">
			<paragraph>On the front side of the widget you can type your message. Note:
			because of a peculiarity of the current WebKit from Apple, you can only
			start typing after you click in the upper left corner of the widget (if
			there is no insertion caret visible). Press Command-Return or click the
			"Take Note" button to save the note to your database.</paragraph>
			<image src="devonthinkpro/widget_devonjotpro_front.jpg" align="left"
			scaling="70%" />
			<paragraph>The area with the "Warning" or "Error" icon will indicate if you
			can take your note. Or if something went wrong when you clicked the "Take
			Note" button it would show an "Error" icon. If you hover your mouse over
			these icons, you can see the exact message on the screen. If your note was
			stored successfully in the application, it would have been erased from the
			widget to make space for a new one. All the information on screen is
			preserved even if you leave Dashboard, as long as you don't close the
			widget.</paragraph>
		</subsection>
		<subsection name="Back Side" id="devonjotpro_back">
			<paragraph>You can flip the widget by clicking the "i" button that appears
			when you move the mouse into the lower right corner of the widget. The back
			side contains some preferences that you can use to customize DEVONjot Pro
			to your needs.</paragraph>
			<image src="devonthinkpro/widget_devonjotpro_back.jpg" align="left"
			scaling="70%" />
			<list>
				<item name="Database">Select the database you want to act the
				widget on or select "Any" to send notes always to the currently
				open database.</item>
				<item name="Group">Specify the group to send the note to.</item>
				<item name="Font">Specify the font and size you want to use to type
				your note. Choose "Auto" for the size to make DEVONjot Pro adjust
				the size automatically when you type more text.</item>
			</list>
			<paragraph>For the group, the following options are available:</paragraph>
			<list>
				<item name="Top or current group">Send the note to the top group if
				no record is selected in the database or the group of the currently
				selected record.</item>
				<item name="Custom">This will display an area where you can type a
				location for a group. You can use the slash '/' character to
				separate groups like in a Unix path.</item>
				<item name="&lt;List of groups&gt;">Optionally a list of current
				groups in the database appears if your database has less than about
				30 groups. If your database has more than that you will not see
				this list. You could use the "Custom Group" feature to select a
				specific group in that case.</item>
			</list>
			<note>If you use multiple databases with ${software}, the widget will warn
			you if the currently open database is different from the one you've
			selected and will prevent you from taking a note. You can also select an
			existing group in the database, but if this group has been removed or
			otherwise invalidated, the widget will also prevent you to save the note.
			You would have to change the preferences or the database and its groups in
			these cases in order to take notes again. When you have chosen a "Custom
			Group", it will always be recreated if it has somehow been
			invalidated.</note>
			<paragraph>Click "Done" to flip the widget back to the front
			side.</paragraph>
		</subsection>
	</section>
	<section name="DEVONsearch" id="devonsearch">
		<paragraph>The DEVONsearch widgets allows you to search your ${software} database
		directly from Dashboard. The widgets lists all results and shows a preview in a
		drawer.</paragraph>
		<subsection name="Front Side" id="devonsearch_front">
			<image src="devonthinkpro/widget_devonsearch_front.jpg" align="left"
			scaling="60%" />
			<paragraph>On the front side of the widget you can enter your search term
			into the search field and click the ${software} icon to start the search
			run. If ${software} isn't running, it will be opened. The result list
			include the name of the found documents and the score.</paragraph>
			<paragraph>Scroll through the results and select them to open a preview
			drawer. Click the yellow up arrow to close the drawer.</paragraph>
			<paragraph>If you double click a result, you will leave the Dashboard to a
			window in ${software} that will display the result.</paragraph>
			<paragraph>If the widget cannot display the contents of the selection, a
			link will be displayed in the preview drawer. When you click the link, you
			will leave the Dashboard to see the result (depending on the type of link,
			either in a browser or an application that understands the file
			format).</paragraph>
		</subsection>
		<subsection name="Back Side" id="devonsearch_back">
			<image src="devonthinkpro/widget_devonsearch_back.jpg" align="left"
			scaling="60%" />
			<paragraph>You can flip the widget by clicking the "i" button that appears
			when you move the mouse into the upper right corner of the widget. The back
			side contains some preferences that you can use to customize DEVONsearch to
			your needs.</paragraph>
			<list>
				<item name="Operator">Choose which search operator you want to use:
				"All Words", "Any Words", "Phrase" or "Wildcards". These options
				correspond to their counterparts in the 
				<reference chapter="windows" section="search">"Search"
				window.</reference></item>
				<item name="Comparison">Choose if you want to search exact,
				case-insensitive or fuzzy. These options correspond to their
				counterparts in the 
				<reference chapter="windows" section="search">"Search"
				window.</reference></item>
			</list>
			<paragraph>Click "Done" to flip the widget back to the front
			side.</paragraph>
		</subsection>
	</section>
</chapter>
