=== 00mjk/SubEthaEdit/documentation/manual/etc/documentation.dtd
<!ELEMENT chapter (#PCDATA | section | paragraph | image | sourcecode | list | note | example)*>
	<!ATTLIST chapter name CDATA #IMPLIED>
	<!ATTLIST chapter edition CDATA #IMPLIED>
	<!ATTLIST chapter id ID #REQUIRED>
	<!ATTLIST chapter edition_lite (yes | no) "yes">
	<!ATTLIST chapter edition_pro (yes | no) "yes">
	<!ATTLIST chapter edition_se (yes | no) "yes">
	<!ATTLIST chapter edition_ee (yes | no) "yes">

<!ELEMENT section (#PCDATA | subsection | paragraph | sourcecode | list | note | example | image)*>
	<!ATTLIST section name CDATA #REQUIRED>
	<!ATTLIST section id CDATA #REQUIRED>
	<!ATTLIST section anchor CDATA #IMPLIED>
	<!ATTLIST section edition_lite (yes | no) "yes">
	<!ATTLIST section edition_pro (yes | no) "yes">
	<!ATTLIST section edition_se (yes | no) "yes">
	<!ATTLIST section edition_ee (yes | no) "yes">

<!ELEMENT subsection (#PCDATA | paragraph | sourcecode | list | note | example | image)*>
	<!ATTLIST subsection name CDATA #IMPLIED>
	<!ATTLIST section id CDATA #REQUIRED>
	<!ATTLIST subsection anchor CDATA #IMPLIED>
	<!ATTLIST subsection id CDATA #IMPLIED>
	<!ATTLIST subsection edition_lite (yes | no) "yes">
	<!ATTLIST subsection edition_pro (yes | no) "yes">
	<!ATTLIST subsection edition_se (yes | no) "yes">
	<!ATTLIST subsection edition_ee (yes | no) "yes">

<!ELEMENT paragraph (#PCDATA | phrase | nameofsoftware | link | reference)*>
	<!ATTLIST paragraph lead CDATA #IMPLIED>
	<!ATTLIST paragraph name CDATA #IMPLIED>
	<!ATTLIST paragraph edition_lite (yes | no) "yes">
	<!ATTLIST paragraph edition_pro (yes | no) "yes">
	<!ATTLIST paragraph edition_se (yes | no) "yes">
	<!ATTLIST paragraph edition_ee (yes | no) "yes">

<!ELEMENT phrase (#PCDATA | nameofsoftware | link | reference)*>
	<!ATTLIST phrase
		edition_lite (yes | no) "yes"
		edition_pro (yes | no) "yes"
		edition_se (yes | no) "yes"
		edition_ee (yes | no) "yes"
	>
	
<!ELEMENT sourcecode (#PCDATA | phrase | nameofsoftware | link | reference)*>
	<!ATTLIST sourcecode
		edition_lite (yes | no) "yes"
		edition_pro (yes | no) "yes"
		edition_se (yes | no) "yes"
		edition_ee (yes | no) "yes"
	>

<!ELEMENT list (#PCDATA | item)*>
	<!ATTLIST list
		edition_lite (yes | no) "yes"
		edition_pro (yes | no) "yes"
		edition_se (yes | no) "yes"
		edition_ee (yes | no) "yes"
	>

<!ELEMENT item (#PCDATA | phrase | link | reference | nameofsoftware)*>
	<!ATTLIST item name CDATA #IMPLIED>
	<!ATTLIST item
		edition_lite (yes | no) "yes"
		edition_pro (yes | no) "yes"
		edition_se (yes | no) "yes"
		edition_ee (yes | no) "yes"
	>

<!ELEMENT note (#PCDATA | link | reference | phrase | nameofsoftware)*>
	<!ATTLIST note
		edition_lite (yes | no) "yes"
		edition_pro (yes | no) "yes"
		edition_se (yes | no) "yes"
		edition_ee (yes | no) "yes"
	>

<!ELEMENT example (#PCDATA | link | reference | phrase | nameofsoftware)*>
	<!ATTLIST example
		edition_lite (yes | no) "yes"
		edition_pro (yes | no) "yes"
		edition_se (yes | no) "yes"
		edition_ee (yes | no) "yes"
	>

<!ELEMENT image (#PCDATA)>
	<!ATTLIST image
		name 		CDATA #IMPLIED
		src			CDATA #IMPLIED
		src_html		CDATA #IMPLIED
		align		(left | center | right) "center"
		scaling		CDATA "8cm"
	>
	<!ATTLIST image
		edition_lite (yes | no) "yes"
		edition_pro (yes | no) "yes"
		edition_se (yes | no) "yes"
		edition_ee (yes | no) "yes"
	>
	
<!ELEMENT link (#PCDATA)>
	<!ATTLIST link
		href CDATA #REQUIRED
	>

<!ELEMENT reference (#PCDATA | nameofsoftware)*>
	<!ATTLIST reference
		chapter CDATA #REQUIRED
		section CDATA #IMPLIED
		subsection CDATA #IMPLIED
	>
	<!ATTLIST reference edition_lite (yes | no) "yes">
	<!ATTLIST reference edition_pro (yes | no) "yes">
	<!ATTLIST reference edition_se (yes | no) "yes">
	<!ATTLIST reference edition_ee (yes | no) "yes">

=== 00mjk/SubEthaEdit/documentation/manual/SubEthaEdit/xml/introduction.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE chapter SYSTEM "../../etc/documentation.dtd">
<chapter name="Introduction" id="introduction">
	<paragraph>Make the dream of the paperless office come true with ${software} and keep all
	your</paragraph>
	<list>
		<item>text and RTF files,</item>
		<item edition_le="no">scanned documents,</item>
		<item>notes,</item>
		<item edition_le="no">e-mails,</item>
		<item edition_le="no">images,</item>
		<item edition_le="no">multimedia files,</item>
		<item>chat logs and</item>
		<item>bookmarks</item>
	</list>
	<paragraph>together in one simple to use database. Integrate both local documents and live
	content from the Internet to keep all project-related information together.</paragraph>
	<paragraph name="Why ${software}">${software} not only stores documents, it also
	facilitates</paragraph>
	<list>
		<item>editing,</item>
		<item>analyzing,</item>
		<item>organizing,</item>
		<item>finding and</item>
		<item>archiving</item>
	</list>
	<paragraph>your documents with its flexible work environment, powerful organization tools
	and built-in AI architecture.</paragraph>
	<paragraph name="Integrated Workspace" edition_le="no">Unlike the Finder, ${software}
	provides an integrated work environment with all the tools you need for working with
	information of all kinds, from simple text to PDFs and multimedia files. Let ${software}
	intelligently assist you with filing documents, finding similar files or searching the
	database instead of digging through thousands of files on your own.</paragraph>
	<paragraph>As a real Mac application, ${software} is also tightly integrated with the
	operating system and its frameworks. It provides a dock menu, and services menu commands
	and makes heavy use of the Safari web browser engine 
	<phrase edition_le="no">and the advanced PDF library</phrase>of Mac OS X 10.4
	Tiger.</paragraph>
</chapter>

=== 00mjk/SubEthaEdit/documentation/manual/shared/_technology.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE chapter SYSTEM "../etc/documentation.dtd">
<chapter name="Technology" id="technology">
	<paragraph>All commercial DEVONtechnologies applications are based on a proprietary AI
	technology, with rock-solid database foundation that allow them to manage large numbers of
	documents or knowledge bits while analyzing them almost instantly at the same
	time.</paragraph>
	<section name="General Concept" id="concept">
		<paragraph>DEVONtechnology, on which all DEVONtechnologies' applications are built,
		is a new technology at the very beginning of its development. DEVONtechnologies
		constantly improves the technology and enhances it for more functionality,
		efficiency, robustness and flexibility.</paragraph>
		<paragraph>Development of the DEVONtechnology is a battle on two main forefronts of
		information processing technology. DEVONtechnologies is working hard on unifying
		both the top-down and the bottom-up AI concepts by imitating high-level functions
		and simulating the basic functionality of natural systems. This leads to highly
		functional, fast and efficient AI systems that can be used in a great variety of
		information processing contexts, such as pattern recognition, signal processing and
		information storage and retrieval.</paragraph>
	</section>
	<section name="Features" id="features">
		<paragraph>The DEVONtechnology is a rock-solid foundation suitable for a variety of
		completely independent applications. Therefore it is ideal for the rapid
		development of a huge range of new database-, signal-processing- and
		language-analysis-driven applications. The ability to deal with any kind of digital
		data makes it extremely flexible.</paragraph>
		<image name="Diagram Database Size" src_html="diagram.jpg" src="diagram.jpg"
		align="center" scaling="8cm" />
		<paragraph>The size of DEVONtechnology-based databases grows logarithmically and
		indexing is completely unnecessary. The break-even point in the picture above,
		where the DEVONthink line crosses the others, depends mainly on the type of the
		stored data. For example, it will be reached much earlier when storing HTML or RTF,
		compared to plain text or even pictures.</paragraph>
		<image name="Diagram UTF" src_html="diagram_utf.jpg" src="diagram_utf.jpg"
		align="center" scaling="8cm" />
		<paragraph>Also, applications based on the DEVONtechnology improve themselves
		continuously (the more data they handle, the better the results), are
		language-independent and iron out any irregularities by applying fuzzy
		logic.</paragraph>
	</section>
	<section name="Structure" id="structure">
		<paragraph>The DEVONtechnology consists of a kernel and several layers. Together
		they perform all the underlying computing, from "simple" data handling to complex
		signal processing.</paragraph>
		<paragraph name="Kernel">The kernel is the foundation for all layers and
		applications and is responsible for data handling, semantic and associative data
		processing, signal processing, fast statistic analyses and all fuzzy algorithms. It
		has to be as fast, flexible, and extensible as possible; it is 64-bit aware and
		uses a generic, proprietary file format (see above) allowing it to verify and
		repair low level data consistency, featuring logarithmic growth of the database and
		logarithmic speed decrease with increasing database size. The DEVONtechnology
		kernel is Unicode-aware, completely language-independent and self-optimizing and
		self-organizing.</paragraph>
		<paragraph name="Layers">The layers form a shell around the kernel and provide
		high-level functions for the applications built on top of them. The database layer,
		for example, is used to store and organize data and supports all kinds of relations
		(1:n, n:1, n:n), hierarchies and freeform databases. No indexing or primary keys
		are required, strings can be unlimited in size and it's possible at any time to
		extend the range of pre-defined data types (Boolean, character, float, double,
		signed, unsigned, string, date, time, blob, color, size, and point). Another layer,
		the XML layer, makes it easy to handle XML code within the DEVONtechnology; it has
		a very small overhead, compared to DOM parsers or available XML databases, requires
		no indexing and supports the tight integration of other databases (and vice
		versa).</paragraph>
	</section>
	<section name="Applications" id="applications">
		<paragraph>Some of the most likely applications for the DEVONtechnology are
		databases (knowledge bases, expert systems, search engines,
		table-of-content-generators, instant data-mining), intelligent agents, encryption,
		compression and archiving. Other uses for DEVONtechnology may be chat-bots,
		context-sensitive help, optical character recognition (OCR), speech analysis,
		recognition and synthesis, staticstics, thesauri and automatic
		translations.</paragraph>
		<paragraph>In particular, applications dependant on processing human language,
		either written or spoken, benefit from the flexible technology foundation. So,
		DEVONtechnologies' main focus in the development of new applications is in these
		areas: databases, "intelligent" agents, text and speech analysis,
		statistics.</paragraph>
		<paragraph>Look forward to see a great range of different applications based on the
		DEVONtechnology. A few have already been announced on the DEVONtechnologies web
		site: 
		<link href="http://www.devon-technologies.com">
		www.devon-technologies.com.</link></paragraph>
	</section>
</chapter>

=== 00mjk/SubEthaEdit/documentation/manual/SubEthaEdit/xml/appendix.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE chapter SYSTEM "../../etc/documentation.dtd">
<chapter name="Appendix" id="appendix">
	<section name="Glossary" id="glossary">
		<paragraph>${software} uses a number of terms you should know when working with the
		application.</paragraph>
		<subsection name="Interface Elements" id="glossary_gui">
			<list>
				<item name="Contextual Menu">The menu that appears when you
				control-click something (with a two-button mouse you can also
				right-click) and gives access to frequently used commands that deal
				directly with the clicked object. Read more about the available
				contextual menus in the 
				<reference chapter="views">"Views"</reference>and 
				<reference chapter="windows">"Windows" chapters.</reference></item>
				<item name="View/Edit Pane">A part of the ${software} 
				<reference chapter="windows" section="main">main
				window</reference>that lets you view a document or, if possible,
				edit it. The view/edit pane displays 
				<reference chapter="views">different views</reference>depending on
				the type of document it shows.</item>
				<item name="View (1)">The layout for a ${software} 
				<reference chapter="windows" section="main">main
				window.</reference>You can change the layout with the commands in
				the 
				<reference chapter="menus" section="view">View
				menu.</reference></item>
				<item name="View (2)">The display for the various document types
				inside the the view/edit 
				<phrase edition_le="no">pane or a 
				<reference chapter="windows" section="document">document
				window.</reference></phrase>
				<phrase edition_pe="no" edition_se="no">pane.</phrase>
				<reference chapter="views">Read more about views
				here.</reference></item>
				<item name="Window" edition_le="no">${software} uses three
				different types of windows, main, document and other windows. 
				<reference chapter="windows" section="main">Main
				windows</reference>show the hierarchy and, in some views, also the
				selected document, whereas 
				<reference chapter="windows" section="document">document
				windows</reference>show documents separately.</item>
				<item name="Window" edition_pe="no" edition_se="no">
				<reference chapter="windows" section="main">${software}
				windows</reference>show the group hierarchy and the selected
				document in the view/edit pane.</item>
			</list>
		</subsection>
		<subsection name="Documents &amp; Groups" id="glossary_documents">
			<list>
				<item name="Database">The collection of all documents stored in
				${software}.</item>
				<item name="Document" edition_le="no">A file in the database, for
				example a plain or RTF text, a PDF or an image. Technically an
				entry in the database with text, RTF, or image content. Sometimes
				referred to as "content".</item>
				<item name="Document" edition_pe="no" edition_se="no">A file in the
				database, a plain or RTF text, or a link. Technically an entry in
				the database with text or RTF content. Sometimes referred to as
				"content".</item>
				<item name="Group">A collection of documents or other groups inside
				the database. Similar to a folder in the file system.</item>
				<item name="Replicant">A second "incarnation" of a document or
				group. Unlike an alias in the file system, a replicant is not a
				real document pointing to another file, the original, but only a
				second entry in the table of contents for the very same document.
				Consequently, there is no original, when you replicate a document
				you'll end up with two replicants.</item>
				<item name="Sheet" edition_le="no" edition_pe="no">Sheets are
				collections of records, structured sets of data. You can use
				records to store for example addresses or list items and view all
				records of a sheet together in a 
				<reference chapter="views" section="sheet">table-like
				view.</reference>Sheets appear in hierarchy lists like folders with
				an expand/collapse triangle in front of their icon.</item>
			</list>
		</subsection>
		<subsection name="Item Properties" id="glossary_itemproperties">
			<list>
				<item name="State">To be done.</item>
			</list>
		</subsection>
	</section>
	<section name="Template tags for Wiki-style links" id="wikitemplates">
		<paragraph>When making a new document by marking some words in an RTF document,
		making them a link and clicking this link, ${software} creates the new document
		using a template you can define in the 
		<reference chapter="preferences" section="editing">preferences panel, "Editing"
		tab.</reference>In this template, you can use the tags below to automatically
		insert the name of the link, the current date or other information. 
		<reference chapter="menus" section="format" /></paragraph>
		<list>
			<item name="%@">Name of link</item>
			<item name="%%">A '%' character</item>
			<item name="%a">Abbreviated weekday name</item>
			<item name="%A">Full weekday name</item>
			<item name="%b">Abbreviated month name</item>
			<item name="%B">Full month name</item>
			<item name="%c">Shorthand for g%X %x", the locale format for date and
			time</item>
			<item name="%d">Day of the month as a decimal number (01-31)</item>
			<item name="%e">Same as %d but does not print the leading 0 for days 1
			through 9</item>
			<item name="%F">Milliseconds as a decimal number (000-999)</item>
			<item name="%H">Hour based on a 24-hour clock as a decimal number
			(00-23)</item>
			<item name="%I">Hour based on a 12-hour clock as a decimal number
			(01-12)</item>
			<item name="%j">Day of the year as a decimal number (001-366)</item>
			<item name="%m">Month as a decimal number (01-12)</item>
			<item name="%M">Minute as a decimal number (00-59)</item>
			<item name="%p">AM/PM designation for the locale</item>
			<item name="%S">Second as a decimal number (00-59)</item>
			<item name="%w">Weekday as a decimal number (0-6), where Sunday is 0</item>
			<item name="%x">Date using the date representation for the locale,
			including the time zone</item>
			<item name="%X">Time using the time representation for the locale</item>
			<item name="%y">Year without century (00-99)</item>
			<item name="%Y">Year with century (such as 1990)</item>
			<item name="%Z">Time zone name (such as Pacific Daylight Time)</item>
			<item name="%z">Time zone offset in hours and minutes from GMT
			(HHMM)</item>
		</list>
	</section>
</chapter>

=== 00mjk/SubEthaEdit/documentation/manual/SubEthaEdit/xml/drawers.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE chapter SYSTEM "../../etc/documentation.dtd">
<chapter name="Drawers" id="drawers">
	<paragraph edition_pe="no" edition_le="no">${software} uses drawers to display the results
	of the "Classify" and "See Also" functions. 
	<phrase edition_le="no" edition_pe="no">Also, drawers show concordance lists of all words
	in a document.</phrase></paragraph>
	<section name="Classify" id="classify">
		<image src="devonthinkpro/drawer_classify.jpg" align="left" scaling="40%"
		edition_le="no" edition_pe="no" />
		<paragraph>The "Classify" drawer appears when you select exactly one document in a 
		<reference chapter="windows" section="main">main window</reference>and click the
		"Classify" button below the view/edit pane. 
		<phrase edition_le="no" edition_se="no">This button is only available in
		"Horizontal Split" and "Vertical Split" views.</phrase>
		<phrase edition_le="no" edition_pe="no">This button is only available in
		"Horizontal Split", "Vertical Split" and "Three Panes" views.</phrase>The
		"Classify" drawer lists up to ten groups in which the selected document would fit
		best (to ${software}'s knowledge) including the path to the group and a graphical
		score of how sure ${software} is about its decision. The tooltip for any entry in
		the list shows the full title and location for it.</paragraph>
		<paragraph>To move the document to one of the suggested groups, select the group
		and click "Move To". For your convenience, ${software} preselects the best fitting
		group if it is sure enough. Double-click a group in the drawer to open it in a
		separate window and drag it into the hierarchy list to move it. Use the Shift and
		Command keys to select more than one target; this generates replicants.</paragraph>
		<note>If the document you are moving has replicants, these are deleted and the
		document is only placed into the new location(s). This prevents that multiple
		replicants are created when you are e.g. classifiying this document again.</note>
		<paragraph>To close the drawer, click the red close button in the lower left
		corner.</paragraph>
		<subsection name="Contextual Menu" id="classify_contextualmenu">
			<paragraph>Use the contextual menu on groups in the "Classify" drawer to
			reveal further commands that you can use to manipulate them.</paragraph>
			<list>
				<item name="Open...">Opens the selected group in a separate 
				<reference chapter="windows" section="main">main
				window.</reference></item>
				<item name="Reveal">Show and select the selected group.</item>
				<item name="Duplicate To &gt; ...">Duplicates the selected group to
				the group you select from the submenu.</item>
				<item name="Replicate To &gt; ...">Replicates the selected group to
				the group you select from the submenu.</item>
				<item name="Move To &gt; ...">Moves the selected group to the group
				you select from the submenu.</item>
				<item name="Label &gt; ...">Changes the label of the selected
				group.</item>
				<item name="State &gt; ...">Shows or changes the state of the
				selected group.</item>
				<item name="Locking &gt; ...">Locks or unlocks the selected
				group.</item>
				<item name="Delete All Instances">Deletes all instances of the
				selected group, i.e. including all replicants (if any).</item>
				<item name="Group">Creates a new group in the top level of the
				database and moves the selected group there.</item>
			</list>
		</subsection>
	</section>
	<section name="See Also, Topics" id="seealso">
		<image src="devonthinkpro/drawer_seealso.jpg" align="left" scaling="40%"
		edition_le="no" edition_pe="no" />
		<paragraph>The "See Also/Topics" drawer appears when you select exactly one
		document in a ${software} 
		<reference chapter="windows" section="main">main window</reference>and click the
		"See Also" button below the view/edit pane. 
		<phrase edition_le="no" edition_se="no">This button is only available in
		"Horizontal Split" and "Vertical Split" views as well as document windows.</phrase>
		<phrase edition_le="no" edition_pe="no">This button is only available in
		"Horizontal Split", "Vertical Split" and "Three Panes" views as well as document
		windows.</phrase>Also, the "See Also/Topcis" drawer opens when you select a topic
		from the "&gt;&gt;" menu in the upper right corner of the view/edit pane or when
		you select a word in a text, web page or PDF document, control-click it and choose
		"See '...'" from the contextual menu.</paragraph>
		<paragraph>The "See Also/Topcis" drawer lists documents that are either similar to
		the selected document ("See Also") or that contain a selected topic or word (topics
		pop-up menu, contextual menu command "See '...'"). Similar to the 
		<reference chapter="drawers" section="classify">"Classify" drawer,</reference>this
		drawer lists the path to the document and a graphical score of how sure ${software}
		is about its decision. The tooltip for any entry in the list shows the full title
		and location for it.</paragraph>
		<paragraph>To display a document in the drawer, select it. For your convenience,
		${software} always lists the originating document at the top of the list, so that
		you can easily go back to the original document. Double-click a document in the
		drawer to open it in a separate window and drag it into the hierarchy list to move
		it.</paragraph>
		<paragraph>To close the drawer, click the red close button in the lower left
		corner.</paragraph>
		<subsection name="Contextual Menu" id="seealso_contextualmenu">
			<paragraph>Use the contextual menu on documents in the "See Also/Topics"
			drawer to reveal further commands that you can use to manipulate
			them.</paragraph>
			<list>
				<item name="Open...">Opens the selected document in a separate 
				<reference chapter="windows" section="main">main
				window.</reference></item>
				<item name="Open with ...">Opens the selected document in the
				default application for its type.</item>
				<item name="Launch URL">Opens the document or web page pointed to
				by the URL field of the selected document.</item>
				<item name="Launch Path">Opens the document pointed to by the Path
				field of the selected document.</item>
				<item name="Reveal">Show and select the document group.</item>
				<item name="Duplicate To &gt; ...">Duplicates the selected document
				to the group you select from the submenu.</item>
				<item name="Replicate To &gt; ...">Replicates the selected document
				to the group you select from the submenu.</item>
				<item name="Move To &gt; ...">Moves the selected document to the
				group you select from the submenu.</item>
				<item name="Label &gt; ...">Changes the label of the selected
				document.</item>
				<item name="State &gt; ...">Shows or changes the state of the
				selected document.</item>
				<item name="Locking &gt; ...">Locks or unlocks the selected
				document.</item>
				<item name="Delete All Instances">Deletes all instances of the
				selected document, i.e. including all replicants (if any).</item>
				<item name="Group">Creates a new group in the top level of the
				database and moves the selected document there.</item>
			</list>
		</subsection>
	</section>
	<section name="Concordance" id="concordance" edition_le="no" edition_pe="no">
		<image src="devonthinkpro/drawer_concordance.jpg" align="left" scaling="40%"
		edition_le="no" edition_pe="no" />
		<paragraph>The "Concordance" drawer appears when you click the "Words" buttons in a
		
		<reference chapter="windows" section="document">document window</reference>opened
		for a text, PDF or HTML/XML document. It lists all words in that document similar
		to the 
		<reference chapter="windows" section="concordance">"Concordance"
		window.</reference></paragraph>
		<paragraph>You can sort the list in the drawer by clicking the title of the column
		you want to use for sorting. Click the column title again to reverse the sorting
		order. If you have changed the contents of the document, click the "Update" button
		to update the concordance list. Double-click any word in the drawer to open the 
		<reference chapter="windows" section="search">"Search" window</reference>with this
		word already filled-in.</paragraph>
		<paragraph>To close the drawer, click the red close button in the lower left
		corner.</paragraph>
	</section>
</chapter>
